### PR TITLE
readme draft

### PR DESCRIPTION
**Pull request by Vollbrecht**
addresses #254

### CODE REVIEW

**Comment by ivmarkov** [comment]
My one concern with this PR is that while it refers to `esp-idf-template`, it is nevertheless *also* containing bits and pieces of information from the installation prerequisites of `esp-idf-template`. To maintain the information up to date, I think for everything related to how to use this crate we do need to simply redirect to `esp-idf-template` and nothing more.

At most, we might provide on top a sample command line how to build the examples.

**Comment by Vollbrecht** [comment]
> My one concern with this PR is that while it refers to `esp-idf-template`, it is nevertheless _also_ containing bits and pieces of information from the installation prerequisites of `esp-idf-template`. To maintain the information up to date, I think for everything related to how to use this crate we do need to simply redirect to `esp-idf-template` and nothing more.
> 
> At most, we might provide on top a sample command line how to build the examples.

My reasoning behind it. 
1) A new user is most likely to hit either esp-idf-hal/svc repository and not the template. Presenting all necessary  setup in a "minimal" way helps winning a potential user to decide if using esp-idf-* is viable. I think this can help highlight that for most people the setup is really fast. I already reduced the setup guide compared to the one in esp-idf-template, and i think this part will not change a lot over the time. 
2) All information that is needed to be going, should be found in one place, not spread out over 10 different places [as long as the information itself is not the size of an book]. ( In that case i think duplication of that information is not bad)  

But if you see it, still otherwise i can remove that section.

**Comment by ivmarkov** [comment]
Yeah. But if you look at the size of the README in `esp-idf-template`... we might be fooling ourselves that we can squeeze this stuff in the README of `esp-idf-svc`. It will simply be incomplete, and over time it will grow all the way to the size of `esp-idf-template`, and then we have to do the same for `esp-idf-hal`, and then probably for `esp-idf-sys` too, and then we'll have the same stuff spread all over 4 places, except slightly different everywhere and probably outdated at most places.

I strongly prefer instead to hyperlink the `esp-idf-template` in the other `esp-idf-*` crates w.r.t. "how to build". This is the purpose of the `esp-idf-template` after all - to get people going with the nitty gritty stuff of installing all the dependencies and so on.

I would rather describe - in the READMEs of `esp-idf-svc` and `esp-idf-hal` the features those crates offer, rather than "new to Embedded, Rust and esp-rs, how to build??" all over again.

**Comment by ivmarkov** [comment]
Not to mention that folks don't want to build `esp-idf-svc` / `esp-idf-hal` per se. These are library crates. What they want instead, is to *use* them in a binary crate which shifts the topic to "how do I build a binary crate that happens to depend on the `esp-idf-*` ecosystem, which is `esp-idf-template` all over again.

The one thing worth mentioning in the readme is the command line which builds the examples. Which is in the CI btw. But even that detail should be mentioned after the hyperlink to `esp-idf-template`, and the wording should assume that the user had succeeded in installing all dependencies depscribed in `esp-idf-template` as well as even a template-generated binary crate first.

**Comment by Vollbrecht** [comment]
Ok, i got you. I will change both README's here and potentialy the esp-idf-sys one to all have same wording and style 1)  directly linking to esp-idf-template. 2) Emphasize your point in all 3 README's that it's an library crate -> setup and usage through esp-idf-template. 3) Updating some info in the esp-idf-template README regarding uninstall + " mention `cargo run` " support

**Comment by ivmarkov** [comment]
I've taken your suggestions (modulo build instructions) and incorporated in the README. Small wording fixes here and there.

**Pull request closed without merging**
