### PR TITLE
Added esp_wifi_sta_get_rssi function in EspWifi

### PR DESCRIPTION
**Pull request by MartinBroers**
I have added the function `esp_wifi_sta_get_rssi` in the Wifi trait. Nothing fancy and works well when connected. I can rename the function if that works better.

### CODE REVIEW

**Review by ivmarkov — CHANGES_REQUESTED** [review]
Can you add the same to `WifiDriver`? Then you can just delegate from `EspWifi::get_rssi` to the driver impl.

**Comment by ivmarkov** [comment]
...and this is not added to the Wifi trait. But let's not do this for now anyway.

**Comment by MartinBroers** [comment]
I've added it to `WifiDriver`. Hope this is the way you meant it?

**Comment by ivmarkov** [comment]
Thanks!

**Pull request merged**
