### PR TITLE
Expose src_addr and des_addr in espnow recv cb

### PR DESCRIPTION
**Pull request by julienvincent**
Currently the espnow bindings for `register_recv_cb` only give a handle on the src_addr from the sending peer. This makes it impossible to determine if the frame was sent on the BROADCAST address.

This change updates the first argument to the receive cb to accept a new `ReceiveInfo` struct containing `src_addr` and `dst_addr`.

This allows writing code along the lines of:

```rust
controller.register_recv_cb(|info, data| {
  if info.dst_addr == &espnow::BROADCAST {
    log::info!("Received broadcast!");
    return;
  }

  // do something else with 'normal' packet.
})?;
```

### CODE REVIEW

**Comment by ivmarkov** [comment]
Can you fix the build for 4.4.x which we (still) support?
If your functionality is impossible to expose for 4.4.x, perhaps you can only do it for 5.x?

**Comment by julienvincent** [comment]
Ah, I didn't spot that this was setup differently for v4 and v5. Would it be acceptable to accept the old `&[u8]` for v4 and the new `ReceiveInfo` for v5?

**Comment by julienvincent** [comment]
@ivmarkov Ok this is compiling now and works locally for me on v5.

I am passing a `ReceiveInfo` to the callback for both v4 and v5 but the `des_addr` will be a initialised slice when compiled for v4.

**Comment by ivmarkov** [comment]
> @ivmarkov Ok this is compiling now and works locally for me on v5.
> 
> I am passing a `ReceiveInfo` to the callback for both v4 and v5 but the `des_addr` will be a `0` initialised slice when compiled for v4.

In `ReceiveInfo`, why not:
```rust
pub des_addr: Option<&'a [u8; 6]>,
```
?

**Comment by ivmarkov** [comment]
Also, `des_addr` sounds a bit weird. Shouldn't it be `dst_addr`?

**Comment by julienvincent** [comment]
> > @ivmarkov Ok this is compiling now and works locally for me on v5.
> > I am passing a `ReceiveInfo` to the callback for both v4 and v5 but the `des_addr` will be a `0` initialised slice when compiled for v4.
> 
> In `ReceiveInfo`, why not:
> 
> ```rust
> pub des_addr: Option<&'a [u8; 6]>,
> ```
> 
> ?

It seems a bit weird to me to do this just to support an old version of IDF. I assume that v4 will be deprecated at some point and then this artifact would remain behind. It would also make the usage in v5 worse - where this would always be a `Some`.

I'd be happy to make the change though. Up to you!

---

> Also, `des_addr` sounds a bit weird. Shouldn't it be `dst_addr`?

I was just copying the terminology from esp-idf verbatim (https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp_now.html#_CPPv417esp_now_recv_info) but I don't have an opinion. Happy to change this to `dst_addr` if you prefer.

**Comment by ivmarkov** [comment]
> It seems a bit weird to me to do this just to support an old version of IDF. I assume that v4 will be deprecated at some point and then this artifact would remain behind. It would also make the usage in v5 worse - where this would always be a `Some`.

Fair enough, leave as is.

> > Also, `des_addr` sounds a bit weird. Shouldn't it be `dst_addr`?
> 
> I was just copying the terminology from esp-idf verbatim (https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp_now.html#_CPPv417esp_now_recv_info) but I don't have an opinion. Happy to change this to `dst_addr` if you prefer.

Sure but maybe we should not copy their mistakes. Either `sor` and `des` or (better) `src` and `dst`.

**Comment by julienvincent** [comment]
@ivmarkov Ok, done 👍🏻

**Comment by ivmarkov** [comment]
Thanks!

**Pull request merged**
