### PR TITLE
Fix esp-idf >= v5.3beta

### LINKED ISSUE #433: Missings fields for Esp-idf >= 5.3 : added additionally fields to esp_vfs_fat_mount_config_t & sdmmc_host_t
They are inlcuded since v5.3beta1 

esp_vfs_fat_mount_config_t now looks like [this](https://github.com/espressif/esp-idf/blob/0453e8608bde98133a427a74ae61d272770b1bfd/components/fatfs/vfs/esp_vfs_fat.h#L122)

and sdmmc_host_t like [this](https://github.com/espressif/esp-idf/blob/0453e8608bde98133a427a74ae61d272770b1bfd/components/sdmmc/include/sd_protocol_types.h#L211)

### PR DESCRIPTION
**Pull request by Vollbrecht**
fix #433

### CODE REVIEW

**Comment by Vollbrecht** [comment]
@AlixANNERAUD since you PR'ed the addition i want you just to notify that upstream esp-idf includes new API's if you are interested in the new fields

**Review by ivmarkov — APPROVED** [review]

**Comment by AlixANNERAUD** [comment]
> @AlixANNERAUD since you PR'ed the addition i want you just to notify that upstream esp-idf includes new API's if you are interested in the new fields

Okay, I'm in exam period but I'm trying to do it this week

**Comment by Vollbrecht** [comment]
> > @AlixANNERAUD since you PR'ed the addition i want you just to notify that upstream esp-idf includes new API's if you are interested in the new fields
> 
> Okay, I'm in the exam period but I'll try to do it this week

Yeah no worries there is no direct action needed, just a headsup for you :D Exams have priority, even if you want to rather work on some code ;)

**Comment by AlixANNERAUD** [comment]
> @AlixANNERAUD since you PR'ed the addition i want you just to notify that upstream esp-idf includes new API's if you are interested in the new fields

I just checked, and the [differences between esp-idf v5.2 and v5.3](https://github.com/espressif/esp-idf/compare/release/v5.2...release/v5.3) (especially `esp_vfs_fat.h`, `sdmmc_host.h` and `sdspi_host.h`), have little impact on the SD card / VFS aspects (just the refactoring of DMA for `sdmmc_host_t` and refactoring of mount configuration for VFS), which doesn't seem to affect the user API, although the implementation seems a bit unclear. In addition, i don't think it's necessary to implement `x_get_dma_info` either.

**Comment by Vollbrecht** [comment]
> > @AlixANNERAUD since you PR'ed the addition i want you just to notify that upstream esp-idf includes new API's if you are interested in the new fields
> 
> I just checked, and the [differences between esp-idf v5.2 and v5.3](https://github.com/espressif/esp-idf/compare/release/v5.2...release/v5.3) (especially `esp_vfs_fat.h`, `sdmmc_host.h` and `sdspi_host.h`), have little impact on the SD card / VFS aspects (just the refactoring of DMA for `sdmmc_host_t` and refactoring of mount configuration for VFS), which doesn't seem to affect the user API, although the implementation for DMA seems a bit unclear. In addition, i don't think it's necessary to implement `x_get_dma_info` either (but I can do it if you want to).

Thanks for the feedback. Its fine i think, if someone needs it he can extend the implementation as needed.

**Pull request merged**
